#!/bin/bash

one=$1
label=${one/\//\\\/}
parts=(${one/\@/ })
version=${parts[1]}
docker images | awk '$1 ~ /'"$label"'/ { if(length($version) == 0) print $3; else print $2 }'
#docker images | awk '$1 ~ /'"$label"'/ { length($version) == 0 ? print $3 : print $2 }'

#d images | tr -s ' ' | cut -d ' ' -f 1-3 | awk '{print $2}'

# Use cases:
#
#  foo/bar   (implied @latest)
#  foo/bar@2.3
#  foo/bar@*
#  foo/bar@2.3*
#  foo/bar@*2.3
