name: CI and Publish

on:
  push:
    tags: ["v*"]
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/setup-action@v1

      - name: Install sbt
        run: |
          cs install sbt
          echo "$HOME/.local/share/coursier/bin" >> $GITHUB_PATH
          sbt sbtVersion

      - name: Build and test
        run: sbt test

      - name: Package targets
        run: |
          mkdir -p target project/target
          tar cf targets.tar target project/target

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbt-targets
          path: targets.tar

  publish:
    name: Publish to Sonatype
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: coursier/setup-action@v1

      - name: Install sbt
        run: |
          cs install sbt
          echo "$HOME/.local/share/coursier/bin" >> $GITHUB_PATH
          sbt sbtVersion

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: sbt-targets

      - name: Unpack
        run: |
          tar xf targets.tar
          rm targets.tar

      - name: Publish to Sonatype
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
        run: sbt ci-release